{
    "name": "ORE website",
    "category": "Website",
    "version": "12.0.1.0",
    "author": "TechnoLibre",
    "license": "AGPL-3",
    "website": "https://technolibre.ca",
    "depends": [
        "website",
        "ore",
        "crm",
        "website_crm",
        "website_form_builder",
        "demo_website_leaflet",
        "portal",
        "auth_signup",
    ],
    "data": [
        "data/ir_attachment.xml",
        "data/ir_ui_view.xml",
        "data/website_page.xml",
        "data/website_menu.xml",
        "templates/website.xml",
        "views/assets.xml",
        "views/portal_templates.xml",
        "views/snippets.xml",
        "views/webclient_templates.xml",
        "views/website_ore_notification.xml",
    ],
    "installable": True,
    "pre_init_hook": "pre_init_hook",
    "post_init_hook": "post_init_hook",
}
