{
    "name": "ORE data",
    "category": "Uncategorized",
    "version": "12.0.1.0",
    "author": "TechnoLibre",
    "license": "AGPL-3",
    "application": True,
    "depends": [
        "ore",
    ],
    "data": [
        "data/ore_occupation.xml",
        "data/ore_origine.xml",
        "data/ore_provenance.xml",
        "data/ore_region.xml",
        "data/ore_ville.xml",
        "data/ore_arrondissement.xml",
        "data/ore_quartier.xml",
        "data/ore_revenu_familial.xml",
        "data/ore_situation_maison.xml",
        "data/ore_type_communication.xml",
        "data/ore_type_service_categorie.xml",
        "data/ore_type_service_sous_categorie.xml",
        "data/ore_type_service.xml",
        "data/ore_workflow.xml",
        "data/ore_workflow_state.xml",
        "data/ore_workflow_relation.xml",
    ],
    "installable": True,
}
