# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl)

from . import (
    ore_arrondissement,
    ore_commentaire,
    ore_demande_adhesion,
    ore_demande_service,
    ore_echange_service,
    ore_echange_service_notification,
    ore_membre,
    ore_membre_interet,
    ore_membre_langue_parle,
    ore_occupation,
    ore_offre_service,
    ore_origine,
    ore_provenance,
    ore_quartier,
    ore_region,
    ore_revenu_familial,
    ore_situation_maison,
    ore_type_communication,
    ore_type_service,
    ore_type_service_categorie,
    ore_type_service_sous_categorie,
    ore_ville,
    ore_workflow,
    ore_workflow_relation,
    ore_workflow_state,
    res_config_settings,
    res_partner,
)
